"""AutoSolver core package."""

from autosolver.cli import solve
from autosolver.core.models import (
    BenchmarkCaseMetric,
    BenchmarkSummary,
    BenchmarkCase,
    BusinessConstraints,
    CanonicalInstance,
    CandidateOption,
    Event,
    ExperimentRecord,
    ExperimentSpec,
    GeoPoint,
    LexicographicScore,
    MatchScore,
    Order,
    OrderDispatch,
    Rider,
    SolveConfig,
    SolveResult,
    ValidationIssue,
    ValidationReport,
    BundleCandidate,
)

__all__ = [
    "BenchmarkCaseMetric",
    "BenchmarkCase",
    "BenchmarkSummary",
    "BusinessConstraints",
    "BundleCandidate",
    "CanonicalInstance",
    "CandidateOption",
    "Event",
    "ExperimentRecord",
    "ExperimentSpec",
    "GeoPoint",
    "LexicographicScore",
    "MatchScore",
    "Order",
    "OrderDispatch",
    "Rider",
    "SolveConfig",
    "SolveResult",
    "ValidationIssue",
    "ValidationReport",
    "solve",
]
